services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - lab2_postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d:ro
      - ./sourcedata:/import:ro
    networks:
      - bigdata-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "${CLICKHOUSE_PORT}:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./sql/clickhouse:/docker-entrypoint-initdb.d:ro
    networks:
      - bigdata-net
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10

  spark-master:
    image: apache/spark:3.5.6
    container_name: spark-master
    hostname: spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      --host spark-master
      --port 7077
      --webui-port 8080
    ports:
      - "7077:7077"
      - "8082:8080"
    volumes:
      - ./spark-app:/opt/spark-app
    networks:
      - bigdata-net

  spark-worker:
    image: apache/spark:3.5.6
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
      --webui-port 8081
      --cores 2
      --memory 2g
    ports:
      - "8081:8081"
    volumes:
      - ./spark-app:/opt/spark-app
    networks:
      - bigdata-net

  spark-submit:
    build:
      context: ./spark-submit
    container_name: spark-submit
    depends_on:
      db:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      spark-master:
        condition: service_started
      spark-worker:
        condition: service_started
    volumes:
      - ./spark-app:/opt/spark-app
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_TABLE: mock_data_raw
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST}
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    networks:
      - bigdata-net

networks:
  bigdata-net:
    driver: bridge

volumes:
  lab2_postgres_data:
  clickhouse_data:
